{{- if .Values.cluster.createNamespace }}

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.cluster.namespace }}
  labels:
    app: {{ template "storageos.name" . }}
    app.kubernetes.io/component: operator
    control-plane: storageos-operator
    chart: {{ template "storageos.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

{{- end }}
