apiVersion: v2
appVersion: "v2.5.0"
description: Cloud Native storage for containers
name: storageos-operator
version: 0.5.0
keywords:
- storage
- block-storage
- volume
- operator
home: https://storageos.com
icon: https://docs.storageos.com/images/logo-helm.svg
sources:
- https://github.com/storageos
maintainers:
- name: DavidMarchant
  email: david@ondat.io
- name:  mhmxs
  email: richard.kovacs@ondat.io
- name: aeroniero33
  email: angelos.perivolaropoulos@ondat.io
